chore(build): use truffle to compile the contracts
truffle is used in the autonity client repo, reusing
the autonity client config ensures that the build is
consistent with the autonity client build

diff --git a/scripts/update_abi b/scripts/update_abi
--- a/scripts/update_abi
+++ b/scripts/update_abi
@@ -1,31 +1,55 @@
 #!/usr/bin/env bash
 
 
-# Autonity client releases are available here: 
+# Autonity client releases are available here:
 # https://github.com/autonity/autonity/releases
-AUTONITY_NODE_COMMIT=ce483153e7c1527c0326e8100b57b102bd702781
-AUTONITY_NODE_REPO=https://github.com/autonity/autonity.git
+AUTONITY_NODE_COMMIT=${AUTONITY_NODE_COMMIT:=ce483153e7c1527c0326e8100b57b102bd702781}
+AUTONITY_NODE_REPO=${AUTONITY_NODE_REPO:=https://github.com/autonity/autonity.git}
 
-echo 
+echo
 echo "============================================================"
-echo "Generating ABI files for Autonity contract from version ${AUTONITY_NODE_TAG}"
-echo "Commit: ${AUTONITY_NODE_COMMIT}"
+echo "Generating ABI files for Autonity contract from:"
+echo "Repository: ${AUTONITY_NODE_REPO}"
+echo "Commit:     ${AUTONITY_NODE_COMMIT}"
 echo "============================================================"
 
+
+# check for required commands
+command -v truffle >/dev/null 2>&1 || { echo >&2 "truffle command was not found"; exit 1; }
+command -v jq >/dev/null 2>&1 || { echo >&2 "jq command was not found"; exit 1; }
+
+# clone the autonity repository
+echo "cloning the repository"
 WORKING_DIR=temp
 mkdir -p ${WORKING_DIR}
 git clone ${AUTONITY_NODE_REPO} ${WORKING_DIR}/autonity
 git -C ${WORKING_DIR}/autonity checkout ${AUTONITY_NODE_COMMIT}
-solc --abi -o ${WORKING_DIR} --overwrite ${WORKING_DIR}/autonity/autonity/solidity/contracts/Autonity.sol
 
+# Compile the contracts
+echo "compiling the contracts"
+pushd ${WORKING_DIR}/autonity/autonity/solidity > /dev/null
+truffle compile | grep "solc:" > solc-version.txt
+popd > /dev/null
+
+# create target directory
 mkdir -p autonity/abi
-for i in `ls ${WORKING_DIR}/*.abi` ; do
-    cat $i | jq --sort-keys > autonity/abi/${i##*/}
+
+# extract abi from json files
+echo "processing abi files"
+contracts=( Autonity IOracle )
+for i in "${contracts[@]}"
+do
+	cat ${WORKING_DIR}/autonity/autonity/solidity/build/contracts/${i}.json | jq --sort-keys .abi > autonity/abi/${i}.abi
 done
 
 # Record how the abi was generated
-solc --version > autonity/abi/solc-version.txt
+echo "recording abi generation details"
+mv ${WORKING_DIR}/autonity/autonity/solidity/solc-version.txt autonity/abi/solc-version.txt
 git -C ${WORKING_DIR}/autonity log --no-decorate --pretty='format:%H' -n 1 > autonity/abi/autonity-commit.txt
+
+
+# cleanup
+echo "cleaning up"
 rm -rf ${WORKING_DIR}
 
 echo
